name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Testing
        run: |
          poetry run coverage run -m unittest tests/teste_cadastro.py
          poetry run coverage report --show-missing
          poetry run coverage xml


